# Generated by Django 2.2.2 on 2019-07-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0002_auto_20190719_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_group', models.CharField(max_length=32, verbose_name='角色')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='permission',
            name='permissions_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RBAC.Permissions_group', verbose_name='分组'),
        ),
    ]
